version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: open-webui_web_1
      APP_PORT: 8542
      PROXY_AUTH_ADD: "false"

  web:
    image: ghcr.io/open-webui/open-webui:ollama@sha256:d9ea4c2067c24d77874eab29d71435c2d04beb98a245e8cd5f71edefc8862108 
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - 8542:8080
    volumes:
      - ${APP_DATA_DIR}/ollama:/root/.ollama
      - ${APP_DATA_DIR}/open-webui:/app/backend/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
